name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build all projects
        run: npx nx run-many --target=build --all

      - name: Run unit tests
        run: npx nx run-many --target=test --all

      - name: Run lint
        run: npx nx run-many --target=lint --all
